### ISSUE TITLE
Works for me only on ios

### ISSUE THREAD

**Issue by azgron** [crazycodeboy/react-native-easy-toast#1]
can you please check it out?

**Comment by crazycodeboy** [comment]
Is the [react-native-easy-toast](https://github.com/crazycodeboy/react-native-easy-toast) not working?

**Comment by azgron** [comment]
Yes. I have tried on Android marshmallow and lollipop, and the react-native-easy-toast didn't work. Do you have any ideas?

**Comment by crazycodeboy** [comment]
![react-native-easy-toast](https://cloud.githubusercontent.com/assets/8716595/18433969/09814fca-791d-11e6-83e9-849cd4c38546.png)  react-native-easy-toast works on android .You can refer to [examples](https://github.com/crazycodeboy/react-native-easy-toast/tree/master/examples)
