### ISSUE TITLE
Element type is invalid: expected a string ( for built-in compoennts) or a class/function (for compsinte compeonts. but got : object. 

### ISSUE THREAD

**Issue by jpca999** [crazycodeboy/react-native-easy-toast#17]
I'm using expo to use this component and i keep getting this error:   

Can you please let me know what am i doing wrong ?

![image](https://user-images.githubusercontent.com/1026325/30255861-7f7efa68-9674-11e7-9ac5-8cceea32d94c.png)

import React, {Component} from 'react';
import {
    TouchableHighlight,
    StyleSheet,
    Text,
    View,
} from 'react-native';

import Toast, {DURATION} from 'react-native-easy-toast'

export default class examples extends Component {
    constructor(props) {
        super(props);
        this.state = {
            position: 'bottom',
            style:{},
        }
    }

    onClick(text, position, duration,withStyle) {
        this.setState({
            position: position,
        })
        if(withStyle){
            this.refs.toastWithStyle.show(text, duration);
        }else {
            this.refs.toast.show(text, duration);
        }
    }

    getButton(text, position, duration,withStyle) {
        return(
            <TouchableHighlight
                style={{padding: 10}}
                onPress={()=>this.onClick(text, position, duration,withStyle)}>
                <Text>{text}</Text>
            </TouchableHighlight>
        )
    }
    render() {
        return (
            <View style={styles.container}>
                <Toast ref="toast" position={this.state.position}/>
                <Toast ref="toastWithStyle" style={{backgroundColor:'red'}} position={this.state.position}/>
            </View>
        );
    }
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#F5FCFF',
    },
});

**Comment by Twinbird24** [comment]
I have the same issue and couldn't find a solution, I ended up just switching to different library.
