### ISSUE TITLE
duration can't be changed

### ISSUE THREAD

**Issue by weidaxu1988** [crazycodeboy/react-native-easy-toast#2]
Awesome project! But the toast last on the screen for around 6 seconds with all kinds of durations.
I've tried 100, 500, length_short, length_long. any idea?

**Comment by crazycodeboy** [comment]
Please upgrade react-native-easy-toast to v1.0.2.[eact-native-easy-toast](https://www.npmjs.com/package/react-native-easy-toast)，The unit is millisecond.
