### ISSUE TITLE
Cannot read property 'show' of undefined

### ISSUE THREAD

**Issue by peyman-hakemi** [crazycodeboy/react-native-easy-toast#87]
im use Toast in functional component:

`const toastRef = useRef();`
    `  <Toast`
       ` ref={toastRef}`
      `  textStyle={{`
        `  color: 'white',`
    `    }}`
     `   position="center"`
   `   />`

i want to show my errors with this
but here is the trick

when i fetch my data and get an answer from the server every thing is OK
but when i have a problem and my try catch get an error i see this warning in yellow box

> Possible Unhandled Promise Rejection (id: 0):
> TypeError: Cannot read property 'show' of undefined

this is my try catch

` try {`
       `const res = await axios.get('/apiAddres');`
      `console.log('get getSpecials are', res.data.data);`
     ` if (res.data.is_successful) {`
       ` setSpecials(res.data.data);`
       ` setLoading(false);`
     ` } else {`
       ` toastRef.current.show(`
         ` <ErrorComponent errors={res.data.message} />,`
        `  10000,`
       ` );`
        `setLoading(false);`
     ` }`
   ` } catch (error) {`
    `  setLoading(false);`
     ` toastRef.current.show('ارتباط با سرور برقرار نمی باشد.', 10000);`
     ` console.log('error getSpecials 2', error);`
     ` // todo show error in screen`
   ` }`

thanks in advance

**Comment by peyman-hakemi** [comment]
soo
here the solution i use for this one

in my catch i just call a function and pass the error with that

catch (error) {
      setLoading(false);
      showError(error.message);
      console.log('error getSpecials 2', error);
    }

**Comment by omeranar1** [comment]
did you solve the problem
